// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJGVuFgI6h-n4xE6BV5zr99HhKDuW1Ssg',
    appId: '1:234247651900:web:87a584aa72e96708db3939',
    messagingSenderId: '234247651900',
    projectId: 'bug-anonymous-auth',
    authDomain: 'bug-anonymous-auth.firebaseapp.com',
    storageBucket: 'bug-anonymous-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9SwWRdNCsh_8ZKURmQBBfX7lHah7xoK4',
    appId: '1:234247651900:android:7440cec1790171d6db3939',
    messagingSenderId: '234247651900',
    projectId: 'bug-anonymous-auth',
    storageBucket: 'bug-anonymous-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzlayOY8LPPTy3IPFr0bPwKPaqp4CTVXU',
    appId: '1:234247651900:ios:cb3d734d088703d7db3939',
    messagingSenderId: '234247651900',
    projectId: 'bug-anonymous-auth',
    storageBucket: 'bug-anonymous-auth.appspot.com',
    iosBundleId: 'com.example.bugAnonymousAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzlayOY8LPPTy3IPFr0bPwKPaqp4CTVXU',
    appId: '1:234247651900:ios:b25cc6cd8ae59462db3939',
    messagingSenderId: '234247651900',
    projectId: 'bug-anonymous-auth',
    storageBucket: 'bug-anonymous-auth.appspot.com',
    iosBundleId: 'com.example.bugAnonymousAuth.RunnerTests',
  );
}
